package org.activityinfo.service.blob;

import com.google.common.base.Strings;
import org.activityinfo.model.resource.Resources;

import javax.annotation.Nonnull;

/**
 * Globally unique Id for a given blob content.
 * Blob Ids are generated by the client.
 */
public final class BlobId {

    @Nonnull
    private final String value;

    private BlobId(String value) {
        assert !Strings.isNullOrEmpty(value);
        this.value = value;
    }

    public static BlobId generate() {
        return valueOf(Resources.generateId().asString());
    }

    public static BlobId valueOf(@Nonnull String value) {
        return new BlobId(value);
    }

    public String asString() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BlobId blobId = (BlobId) o;

        if (!value.equals(blobId.value)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }
}
